// <auto-generated />
using System;
using BitCoio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitCoio.Migrations
{
    [DbContext(typeof(CorretoraContext))]
    partial class CorretoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitCoio.Entities.Carteira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCarteira")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("BitCoio.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarteiraEnvioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarteiraRecebimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraEnvioId");

                    b.HasIndex("CarteiraRecebimentoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("BitCoio.Entities.Transacao", b =>
                {
                    b.HasOne("BitCoio.Entities.Carteira", "CarteiraEnvio")
                        .WithMany()
                        .HasForeignKey("CarteiraEnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitCoio.Entities.Carteira", "CarteiraRecebimento")
                        .WithMany()
                        .HasForeignKey("CarteiraRecebimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteiraEnvio");

                    b.Navigation("CarteiraRecebimento");
                });
#pragma warning restore 612, 618
        }
    }
}
